### ISSUE TITLE
Authorship article is wrong for Bamberg

### ISSUE THREAD

**Issue by 48656c6c6f20576f726c6421** [UBA-PSI/psi-thesis-guide#10]
https://github.com/UBA-PSI/psi-thesis-guide/blob/0efa282a224f072f5783694d9203aaeeb997a23d/degree-thesis/en/main.tex#L320

WIAI BA/MA Apo the article is §9Abs.12

**Comment by sxxs** [comment]
Thanks. Fixed by c2750a5d601418c38198dc92fb538ecde6cd2768
